### ISSUE TITLE
Error: Command failed: Invalid Parameter - -set

### ISSUE THREAD

**Issue by tnbalu** [AlexDisler/cordova-icon#38]
Any idea how to solve this?
D:\projects\poc\mobile\abcdxapp>cordova-icon

 Checking Project & Icon

  √  platforms found: ios, android
  √  icon.png exists
  √  config.xml exists

 Generating Icons for ios

{ [Error: Command failed: Invalid Parameter - -set
] timedOut: false, killed: false, code: 4, signal: null }

D:\projects\poc\mobile\abcdxapp>

**Comment by BrunoCartier** [comment]
Hi,

Are you **absolutely** sure ImageMagick is installed and available ? It's a requirement.
See #21, #25 and #36 that are possibly relative.

**Comment by SeanBlevins** [comment]
Hi,

I had this same issue on Windows.
cordova-icon is trying to call the convert program of ImageMagick. It turns out Windows already has a convert program and even if you add ImageMagick to your PATH the Windows 'convert' will be called by cordova-icon.

I managed to solve the problem by providing the full path to ImageMagick in the imagemagick.js file in cordova-icon.

Open imagemagick.js which you will find in the <your npm install folder>/cordova-icon/node_modules/imagemagick/
And change line 255
exports.convert.path = "convert";
to
exports.convert.path = "C:\\Program Files\\ImageMagick-6.9.1-Q16\\convert";
or whatever your ImageMagick install folder is.

This solution also works for cordova-splash on windows

**Comment by lastboy** [comment]
Can you please fix the Readme?

I had the same issue, according to this link: http://stackoverflow.com/questions/26938411/cordova-icon-gives-error-on-run#26938531
It's correct that you have to install ImageMagick when running on Windows

**Comment by movesax** [comment]
With the latest imagemagick, you have to check the box to install the legacy tools on windows.

**Comment by BrunoCartier** [comment]
Thanks for your feedback. The `README` will soon be clearer about this.

**Comment by osro** [comment]
I would suggest that the README would also say that you need to check the legacy tools from the windows installation. Without that you still get the error.

**Comment by gsiciliano** [comment]
I suggest to check the installation of ImageMagick... in windows i had the same issue and i solve checking "Install legacy utilities (e.g. convert)" flag during installation process.
I hope this may helps

**Comment by skout90** [comment]
@SeanBlevins I love you!!! Thanks alot!!
