### ISSUE TITLE
Usage outside of cordova

### ISSUE THREAD

**Issue by morenoh149** [AlexDisler/cordova-icon#46]
This is a really useful tool. But now I'm doing react native. Anyway drop the dependency that the tool be run from a cordova project?

**Comment by BrunoCartier** [comment]
It is possible & would require only a little amount of code changes.

But since the name of the repo is `cordova-icon`, we won't do it here, since `cordova` is the only aimed framework. You can try to fork the repo and make your own version :smile:

Or, would something like [mobicon-cli](https://github.com/SamVerschueren/mobicon-cli) fit your needs?

**Comment by morenoh149** [comment]
perhaps mobicon-cli is good. Thanks for that. You're right would not make sense to extend this project to support non cordova targets due to the name.
