### ISSUE TITLE
Android Icon doesn't update

### ISSUE THREAD

**Issue by gdevise** [AlexDisler/cordova-icon#48]
I change my icon.png... When I run whith android CLI I keep old icon... On ios I have the new one. 
I tried to delete platforms folders and re install but I keep the old bad icon... 
I forget something?

**Comment by oliverhuynh** [comment]
Yes, correct, This is the issue I'm facing as well. @AlexDisler can you take a look at this issue?

**Comment by tomchambers2** [comment]
I'm also experiencing the issue in iOS - I ran the script once, edited icon.png and splash.png but neither updated.

**Comment by tomchiverton** [comment]
Me too. Update the master icon.png, rerun and the output looks OK but nothing is updated.

Even purging all the files first (` find www/platforms/ -type f -name '*png' -exec rm {} \; `) does not work. Something must be checking for the folders and skipping the work if they are there ?

**Comment by AlexDisler** [comment]
if you're using a cordova version lower than 6.0.0 try:

```npm i -g cordova-icon@0.2.0```

**Comment by jamieowen** [comment]
I'm having a similar problem since updating to the new version.
I could run before with the single icon.png and things worked fine for IOS/Android.

Now when running I see the first 'Checking Project & Icon' heading and all is ok. Then all I see is 'Generating Icons for ios' and the process exits.

I have imagemagick installed and have tried using both the seperate icon-android/ios.png files and single icon.png.

Any help would be appreciated!

**Comment by jamieowen** [comment]
Seems like my error is related to a problem trying to create the folders to export icons to.
iOS output is targeting /Images.xcassets/AppIcon.appiconset/

And the line https://github.com/AlexDisler/cordova-icon/blob/master/index.js#L171
is failing trying to do recursively create the the nested folder structure..

if i get time i'll have to do a pull request :) 
you could use https://www.npmjs.com/package/wrench or something...

**Comment by AlexDisler** [comment]
Should be resolved by https://github.com/AlexDisler/cordova-icon/pull/69
